### ISSUE TITLE
Offering myself to help with basic and simple issues.

### ISSUE THREAD

**Issue by felipegutierrez** [Metalnx/metalnx-web#12]
Dear @ajguerra and all collaborators.

I am working in a project that uses iRODS and our team really appreciated Metalnx-web to be full integrated in our project. We saw that the project started only eight months ago and we are seriously thinking to ask you to let us collaborate with this project. We discussed here that it is not worth to "rebuild a wheel".
So, I am proposing to offer my help to collaborate with this open-source project and start with small and basic issues that you can assign to me and also evaluate before to merge on the master branch. Actually my goal is to solve the issues to query all metadata and files through Metalnx-web, but I believe it is necessary to get confidence on the project and build a trust collaborative with all developers.
I already used a lot open-source projects but never collaborate with one. If you would like to see my experience with Java you can check my [web-site](https://sites.google.com/site/felipeogutierrez/Home/diaadia) and also my [resume](https://docs.google.com/document/d/1lM3aV9-0ECB5u4Zx7IinJtYjvX3qFL6_4s-YrzQoW7M/edit?usp=sharing).

Sorry, but I have no privileges to mark the issue as a question.

Best Regards,
Felipe

**Comment by ajguerra** [comment]
@felipegutierrez we are very happy to have your help. 

It is very good to know that Metalnx would be part of your project. You are more than welcome here.

I see that you want to work on the metadata & files search. Interesting. This is actually in area that we wanted to improve (there are many things that can be done for different purposes) but never got enough time to focus more on it. Feel free to change it and make a pull request.

As an advice, if you want to start with the code, take a look at how we implemented users and groups. These were the two features we implemented first and they are quite straightforward. Post any questions here, we'll be answering them along the way as fast as we can.

BTW, we did not forget your PAM issue. We are working on that on the background. Check out this [post](https://github.com/michael-conway/dockertests/issues/1) if you wanna follow the thread. We are getting there! A new version of Jargon should be out soon with SSL issues fixed. 

Welcome to Metalnx!

Regards,

Arthur

**Comment by felipegutierrez** [comment]
Hi @ajguerra , 

Thanks for your response.

I think someone forgot to commit the class com.emc.metalnx.utils.EmcMetalnxVersion on the emc-metalnx-shared project. When I imported the projects into my eclipse the classes EmcMetalnxVersionHandlerInterceptor and UITest are using this class and the package emc-metalnx-shared/src/main/java/com.emc.metalnx.utils is empty.

**Comment by ajguerra** [comment]
The EmcMetalnxVersion class is generated by Maven during the build process. 

In order for Maven to automatically create it you need to specify the `generate-sources` phase at the Maven build lifecycle (for more information check out this [link](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html)).

I usually run `mvn clean package install generate-sources` to build the project.

**Comment by felipegutierrez** [comment]
Hello @ajguerra , 
I could generate the war file and deploy it on my tomcat (not production machine). To test some functions I am trying to connect my web app at the iRODS VM, but the app is configured to access the localhost, which is normal. To change this I edited the files /emc-metalnx/emc-metalnx-web/src/main/conf/dev/database.properties , irods.environment.properties and mysql.properties (db.url, db.username, db.password). But the web app persists to try to connect at localhost. On my catalina log shows:

```
2017-01-26 16:21:34 WARN  SqlExceptionHelper:143 - SQL Error: 1045, SQLState: 28000
2017-01-26 16:21:34 ERROR SqlExceptionHelper:144 - Access denied for user 'metalnx'@'felipes-mbp.amc.nl' (using password: YES)
2017-01-26 16:21:34 ERROR IRODSAuthenticationProvider:119 - Could not authenticate user:
```

Sorry to append my questions here on the same thread. But I cannot think other place to ask and I think is not good to create another question just for that.

Kind Regards.

**Comment by felipegutierrez** [comment]
Hello @ajguerra ,
I deployed the app on a tomcat at the same machine of the database and I got the same error access denied for localhost. So I wondering which version of MySQL are you using? I am using MySQL 5.6. I think is the lib version problem.

thank you

**Comment by ajguerra** [comment]
@felipegutierrez I just installed MySQL 5.7 and it worked fine. Trying upgrading it and see if it changes anything. Also, check out this [post](http://stackoverflow.com/questions/1559955/host-xxx-xx-xxx-xxx-is-not-allowed-to-connect-to-this-mysql-server) about MySQL user access configuration. It's a good source.

Let me know whether or not you succeed.

**Comment by felipegutierrez** [comment]
I got what I was missing. the file security.properties uses encoded password for database and irods.
encoded.properties=db.password,jobs.irods.password
So, I took out this parameters and I could login. Thank you anyway!

**Comment by ajguerra** [comment]
Good catch! You don't need to have anything on the `encoded.properties` file since you're modifying them directly. This file is useful when configuring iRODS and DB params via setup script.

**Comment by ajguerra** [comment]
@felipegutierrez check out the 1.1.0 version we just released! Let us know if you find any issues.

Thx!

**Comment by felipegutierrez** [comment]
Hi @ajguerra , I will. we are improving another functions on our system and when I have time I will install the new version of Metalnx-web. By the way, did you think about how we can merge the code I commit at https://github.com/felipegutierrez/metalnx-web ? I developed the code to use MySQL 5.6.

**Comment by ajguerra** [comment]
That's ok @felipegutierrez . We have made a couple changes on our workflow strategy that is worth taking a look at. Check out our [Wiki](https://github.com/Metalnx/metalnx-web/wiki).

Despite of that, I looked at our code. Btw, nice job! It will be very useful and we are going to merge it into the repository. 

I just have a suggestion on the controller part. You are doing all the checks to know which database is running underneath Metalnx, so you can call a service with the correct SQL. I think we could improve that by moving this DB checks out of the service layer and leave the controller as simple as possible. 

It shouldn't be the controller's job to know whether or not Metalnx is running against MySQL, Postgres or Oracle. My idea is to move all the logic from the controller to the service layer (maybe a special service to create SQLs based on the DB?).

What do you think?

Thanks for your time on this!

--
Arthur
