### ISSUE TITLE
Docker container not found

### ISSUE THREAD

**Issue by kulnor** [Metalnx/metalnx-web#13]
Just tried to pull this from Docker but the image is not found. Is the container version still being maintained/built?
```
docker pull arthurguerra/metalnx
Using default tag: latest
Error response from daemon: manifest for arthurguerra/metalnx:latest not found
```

**Comment by ajguerra** [comment]
@kulnor thanks for you comment. We're working on a new version of Metalnx and its docker image is one of the things we'll be updating too. It should be available shortly.

**Comment by ajguerra** [comment]
Hi @kulnor ,

Sorry for the long delay. Try `docker pull metalnx/metalnx-web:1.1.0-latest`. 

You should be able to get the latest version now.

Thx!

**Comment by kulnor** [comment]
Thanks! Will check out asap.

**Comment by ajguerra** [comment]
hi @kulnor , have you had the time to check out Metalnx 1.1.0?

Cheers!
