### ISSUE TITLE
Cannot see anything at /

### ISSUE THREAD

**Issue by carrgilson** [Metalnx/metalnx-web#14]
The root of all zones fails to list any collections (zones) and just shows the "No matching records found" message.

**Comment by felipegutierrez** [comment]
I am working on it ..... [link](https://github.com/Metalnx/metalnx-web/issues/5)

**Comment by ajguerra** [comment]
Hi @carrgilson,

Federatation is on our roadmap, but it is currently not supported by Metalnx.

Thx.
