### ISSUE TITLE
"Save preferences" for "rodsadmin" user changes type to "rodsuser"

### ISSUE THREAD

**Issue by kuntzagk** [Metalnx/metalnx-web#18]
Hi,

we noticed that opening the "Preferences" page and pressing "Save" changes user_type_name from "rodsadmin" to "rodsuser"

**Before:**
```
[admin@server ~]$ iadmin lu User
user_id: 16818
user_name: User
user_type_name: rodsadmin
zone_name: testZone
user_info:
r_comment:
create_ts 2017-05-03.17:18:02
modify_ts 2017-06-30.14:14:29
```
**After:**
```
[admin@server ~]$ iadmin lu User
user_id: 16818
user_name: User
user_type_name: rodsuser
zone_name: testZone
user_info:
r_comment:
create_ts 2017-05-03.17:18:02
modify_ts 2017-06-30.14:15:58

```

This is metalnx-web 1.2.1.

regards, Andreas

**Comment by ajguerra** [comment]
What version of Metalnx are you using?

**Comment by kuntzagk** [comment]
Until a moment ago I thought I was using 1.2.1. I build that from source and installed it (to fix the permissions bug we talked about)

But the "About" button still says "1.1.1-DEV"

**Comment by ajguerra** [comment]
You're right. There's a mistake on that. But, if you can, try to upgrade to 1.3.0 to see if the problem persists.

**Comment by kuntzagk** [comment]
Yeah, I just noticed that you forgot to update pom.xml for version 1.2.0 
I will build 1.3.0 now

**Comment by kuntzagk** [comment]
Problem is still present in 1.3.0. 
Please note that I changed `irods.auth.scheme` to `PAM`

**Comment by ajguerra** [comment]
I just set up an iRODS 4.1.10 instance and got an environment similar to yours: `rods` with STANDARD auth and another one using PAM. I went to the preferences page like you did, but there was no change on the user type. Can you walk me through the steps you made to double check if I hadn't missed something?

**Comment by kuntzagk** [comment]
At start I make the user an rodsadmin
```
[mywtl@by-hcrdev2 ~]$ iadmin moduser eqogg type rodsadmin
[mywtl@by-hcrdev2 ~]$ iadmin lu eqogg
user_id: 16818
user_name: eqogg
user_type_name: rodsadmin
zone_name: testZone
user_info:
r_comment:
create_ts 2017-05-03.17:18:02
modify_ts 2017-07-04.14:15:41
```
Now I login as "eqogg". The user_type stays rodsadmin
```
[mywtl@by-hcrdev2 ~]$ iadmin lu eqogg
user_id: 16818
user_name: eqogg
user_type_name: rodsadmin
zone_name: testZone
user_info:
r_comment:
create_ts 2017-05-03.17:18:02
modify_ts 2017-07-04.14:15:41
```
I change to the dashboard (by editing the URL since I do not see a Dashboard link). Still rodsadmin
```
[mywtl@by-hcrdev2 ~]$ iadmin lu eqogg
user_id: 16818
user_name: eqogg
user_type_name: rodsadmin
zone_name: testZone
user_info:
r_comment:
create_ts 2017-05-03.17:18:02
modify_ts 2017-07-04.14:15:41
```
Now I change to "Preferences" and press "Save"
```
[mywtl@by-hcrdev2 ~]$ iadmin lu eqogg
user_id: 16818
user_name: eqogg
user_type_name: rodsuser
zone_name: testZone
user_info:
r_comment:
create_ts 2017-05-03.17:18:02
modify_ts 2017-07-04.14:16:27
```

**Comment by ajguerra** [comment]
Odd. Even on a fresh installation you didn't see the dasboard page coming up? It should be the first page a rodsadmin sees as soon as he's logged in.

**Comment by kuntzagk** [comment]
No, what comes up it the "Collections" page.

**Comment by ajguerra** [comment]
Can you capture the tomcat logs right after you click on "Save" on the preferences page and post it here?
