### ISSUE TITLE
Implement a mechanism to check if the MSI package is installed in all machines of the grid

### ISSUE THREAD

**Issue by ajguerra** [Metalnx/metalnx-web#8]
Currently, an administrator cannot tell (from the UI) if all machines in the grid have the Metalnx MSI package installed.

Desired behavior: show whether or not the MSI package is fully installed & operational (MSI package installed in **all** machines)

**Comment by ngmenyen** [comment]
Closed on release [1.1.0](https://github.com/Metalnx/metalnx-web/tree/1.1.0)
